id: P7E0EE111
initial_creation_type: input
source_metadata:
  title: Sakya Lotsawa Jamyang Kunga Sönam
  parent: 2. Collected works
  source: https://sakyalibrary.com
  bases:
    d65e:
      title: གསན་ཡིག་ཐོས་པའི་རྒྱ་མཚོ་རིན་པོ་ཆེ་པདྨ་རཱ་གའི་ཕྲེང་བ་ལ།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: d65e.txt
      order: 1
    18d3:
      title: གསན་ཡིག་སྐབས་དང་པོ། རྗེ་བཙུན་དམ་པ་རྡོ་རྗེ་འཆང་རཏྣ་ཝརྡྷའི་ཞལ་ལས་སྡོམ་པ་གསུམ་སོགས་ཉེ་བར་ནོས་པའི་སྐབས་དང་པོའོ།།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: 18d3.txt
      order: 2
    93f0:
      title: གསན་ཡིག་སྐབས་གཉིས་པ། རྗེ་བཙུན་འཇམ་པའི་དབང་མ་ཧོ་པཱ་དྷྱཱ་ཡ་བསོད་ནམས་ལེགས་པའི་འབྱུང་གནས་རྒྱལ་མཚན་ལས་རྡོ་རྗེ་ཐེག་པ་སོགས་ཉེ་བར་ནོས་པའི་སྐབས་གཉིས་པའོ།།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: 93f0.txt
      order: 3
    81a2:
      title: གསན་ཡིག་སྐབས་གསུམ་པ། རྗེ་བཙུན་རྣལ་འབྱོར་དབང་ཕྱུག་སེམས་དཔའ་ཆེན་པོ་བུདྡྷ་རཏྣ་ཤྲཱི་བྷ་དྲའི་ཞལ་ལས་རྡོ་རྗེ་ཐེག་པ་སོགས་ཉེ་བར་ནོས་པའི་སྐབས་གསུམ་པའོ།།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: 81a2.txt
      order: 4
    cea3:
      title: གསན་ཡིག་སྐབས་བཞི་པ། རྒྱལ་བ་འདྲེན་པ་འཆི་མེད་དབང་པོ་སོགས་ཉེ་བར་ནོས་པའི་སྐབས་བཞི་པའོ།།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: cea3.txt
      order: 5
    5bd1:
      title: གསན་ཡིག་སྐབས་ལྔ་པ། ཐུན་མོང་མ་ཡིན་པ་ཡོངས་སུ་རྫོགས་པ་ཉེ་བར་ནོས་པའི་སྐབས་ལྔ་པའོ།།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: 5bd1.txt
      order: 6
    4dda:
      title: གསན་ཡིག་སྐབས་དྲུག་པ། བྲན་བདུད་ནག་པོའི་རྗེས་གནང་ལ་སོགས་ཉེ་བར་ནོས་པའི་སྐབས་དྲུག་པའོ།།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: 4dda.txt
      order: 7
    84c4:
      title: གསན་ཡིག་སྐབས་བདུན་པ། དུས་ཀྱི་འཁོར་ལོ་སོགས་ནང་གི་ཟབ་དོན་མཆོག་རྣམས་ཐོས་ཚུལ་སྨྲོས་པའི་སྐབས་བདུན་པའོ།།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: 84c4.txt
      order: 8
    8f54:
      title: མཁན་ཆེན་བསོད་ནམས་ལྷུན་གྲུབ་ཀྱི་རྣམ་ཐར་བློ་གསལ་ཀླུའི་དབང་པོའི་གཙུག་གི་ནོར་བུ་ཞེས་པ།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: 8f54.txt
      order: 9
    15b6:
      title: འཇམ་དབྱངས་སངས་རྒྱས་རིན་ཆེན་གྱི་རྣམ་ཐར་དགེ་ལེགས་རིན་པོ་ཆེའི་གཏེར་ཞེས་བྱ་བ་དང་།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: 15b6.txt
      order: 10
    a6d1:
      title: དེའི་ཁ་སྐོང་ཨུཏྤལའི་ཆུན་པོ།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: a6d1.txt
      order: 11
    46ad:
      title: ཡོན་ཏན་རྒྱ་མཚོ་མའི་ཚིག་དོན་གྱི་དོགས་ཆོད་མ་རིག་མུན་སེལ།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: 46ad.txt
      order: 12
    ef94:
      title: རྒྱ་ནག་རྒྱལ་པོ་ལ་ཕུལ་བའི་ཞུ་ཡིག མངའ་རིས་རྫོང་ཁར་མངའ་བདག་རྒྱལ་པོ་ལ་གནང་བ།  གློ་བོ་མཁན་ཆེན་བསོད་ནམས་ལྷུན་གྲུབ་ལ་ཕུལ་བའི་ཞུ་ཡིག་ཉིས་འབིགས་གཅིག་དང་བཞི།  ཞ་ལུ་ལོ་ཆེན་ལ་ཕུལ་བའི་ཞུ་ཡིག
        ཨེ་ཝྃ་ཆོས་ལྡན་གྱི་འབུལ་སྡུད་པ་དགེ་འདུན་དཔལ་བཟང་ལ་གདམས་པ།  ཡིག་མཁན་ཟླ་གྲགས་ལ་གནང་བའི་བཀའ་ཤོག་གཉིས།
        ལོ་དགོན་པའི་སྤྱན་སྔ་ལ་གནང་བའི་བཀའ་ཤོག་སྡེབ་སྦྱོར་མེད་པ་གཅིག་དང་། ཡོད་པ་གཉིས་ཏེ་གསུམ།
        བླ་མ་སྒྲ་ཚད་པ་དཀོན་མཆོག་རྒྱ་མཚོ་ལ་གནང་བའི་བཀའ་ཤོག བྱང་པ་ཆོས་རྗེ་རིན་ཆེན་བཟང་པོ་ལ་གནང་བའི་བཀའ་ཤོག་གཉིས།
        ཐུབ་བསྟན་རྣམ་རྒྱལ་གྱི་མཁན་པོ་ཆོས་རྗེ་བློ་གྲོས་རབ་ཡངས་པ་ལ་གནང་བའི་བཀའ་ཤོག རབ་འབྱམས་པ་ཀུན་ཚེ་ལ་གནང་བའི་བཀའ་ཤོག
        སྨིན་དྲུག་ལོ་ཙཱ་ལ་གནང་བའི་བཀའ་ཤོག གདོང་དགའ་བ་ཀུན་སྤངས་ཚེ་རིང་གྲགས་པ་ལ་གནང་བའི་བཀའ་ཤོག
        ལྷུན་རྩེ་མཁན་པོ་ཐམས་ཅད་མཁྱེན་པ་ལ་གནང་བའི་བཀའ་ཤོག འདོལ་ཁ་རྒྱལ་པོ་ལ་གནང་བའི་བཀའ་ཤོག
        རྒྱལ་མཁར་རྩེར་གནང་བའི་བཀའ་ཤོག་གཉིས།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: ef94.txt
      order: 13
    84cf:
      title: སེང་གེ་རྩེ་པ་ལ་གནང་བའི་བཀའ་ཤོག་དགེ་ལེགས་ཀྱི་ཚིགས་སུ་བཀའ་དམ་གཅིག་དང་བཞི།  གཞིས་ཁ་རིན་སྤུངས་པ་དཔོན་བློན་སོགས་ལ་གནང་བའི་བཀའ་ཤོག་དགུ་དང་།
        སྣར་ཐང་པས་རྩོམ་གྲོགས་ཞུས་པ་གཅིག ཚོང་འདུས་པ་ལ་གནང་བའི་བཀའ་ཤོག གནས་གསར་བ་ལ་གནང་བའི་བཀའ་ཤོག
        གནས་པ་ལ་གནང་བའི་བཀའ་ཤོག་གཉིས། རྩེད་པ་ནམ་མཁའ་ལ་གནང་བའི་བཀའ་ཤོག རིན་ཆེན་རྩེ་བའི་གཉེར་པ་དཀྱིལ་མཁར་སེང་སྡིང་པ་ལ་གནང་བའི་དྲིས་ལན་བཀའ་ཤོག
        ཁམས་ཀྱི་འབུལ་སྡུད་པ་བླ་མ་སྒྲ་ཚད་པ་དཀོན་མཆོག་རྒྱ་མཚོ་དགེ་སློང་ནམ་མཁའ་རྩེ་མོ་རྟ་འབུལ་མདོ་སྔགས་རབ་འབྱམས་པ་ཀུན་དགའ་དཔལ་འབྱོར་རྣམས་ལ་གནང་བའི་ལམ་ཡིག་སྡེ་ཚན་གསུམ།
        ཡིག་མཁན་ཟླ་གྲགས་ལ་གནང་བའི་གདམ་པ། མཁར་སྤེ་རབ་འབྱམས་པ་བློ་གྲོས་རབ་གསལ་གྱི་དྲིས་ལན་གཉིས།
        རབ་འབྱམས་པ་དབང་ཕྱུག་རྒྱལ་མཚན་ལ་གནང་བའི་གདམ་པ། གདོང་དགའ་བ་ཀུན་སྤངས་ཆོས་ལ་བསྐུལ་བའི་གཏམ།
        བྱས་འགྱུར་པའི་སྒྲུབ་ཆེན་རྣམས་ལ་དགེ་སྦྱོར་བསྐུལ་འདེབས། སྣར་ཐང་སྟོང་དཔོན་དཔོན་བློན་ལ་གདམ་པ་གཉིས།
        རིགས་དྲུག་འཁོར་བའི་སྡུག་བསྔལ་གྱི་སྣང་ཚུལ་རྩོམ་འཕྲོ་གཅིག རྗེ་ཉིད་རང་གི་ཐུགས་དམ་སྨོན་ལམ་ཚིགས་བཅད་མ།
        དབུ་རྩེ་རྙིང་མ་དང་སྒོ་རུམ་གྱི་རྟེན་གསུམ་རྣམས་ཀྱི་དཀར་ཆག་ཚིགས་བཅད་གཉིས། ཚེ་ལྷ་དང་ནོར་ལྷའི་ཚིགས་བཅད་ཤླཽ་ཀ་གཉིས།
        རྗེ་བཙུན་འཇམ་དབྱངས་གཟི་འོད་འབར་བའི་དྲུང་དུ་རྗེ་ཉིད་ཀྱི་སྣམ་སྦྱར་ཕུལ་བའི་ཁ་ཡིག
        གསེར་ཁང་ན་བཞུགས་ཡོངས་འཛིན་དཀོན་མཆོག་འཕེལ་བའི་དགོངས་པ་རྫོགས་ཐབས་སུ། རྗེ་ཉིད་ཀྱིས་བཞེངས་པའི་བླ་མ་རིན་འབྱུང་གི་སྙན་དར་ཁ་ཡིག
        རྗེ་སངས་རྒྱས་རིན་ཆེན་གྱི་ནང་རྟེན་གླིང་ཁ་ན་བཞུགས་པའི་ཐུབ་པའི་སྙན་དར་ཁ་ཡིག སྒོ་རུམ་དང་།
        ནང་སོའི་དགོན་ཁང་དུ། གཞིས་རིན་སྤུངས་ནས་གཏོར་གསོས་གནང་སྐབས་ཀྱི་སྙན་དར་ཁ་ཡིག་ལེ་ཚན་དགུ།
        རྩེད་པ་ནམ་མཁས་ཆོས་སྐྱོང་ཐུན་མོང་དུ་ཕུལ་བའི་སྙན་དར་ཁ་ཡིག་གཅིག་བསྲུབས་ན་བཞུགས་ཡོད།
        ཆོས་རྗེ་དཀོན་མཆོག་ཚུལ་ཁྲིམས་པའི་གདུང་རྟེན་རྒྱལ་རྩེ་ན་བཞུགས་པའི་དངུལ་གྱི་མཆོད་རྟེན་ལ་མངགས་པ་བཀྲ་ཤིས་ཀྱི་མགྲིན་དབྱངས་ཞེས་པ་གཅིག
        དཔལ་དུས་ཀྱི་འཁོར་ལོ་ལ་བསྟོད་པ། གུར་མགོན་ལ་བསྟོད་པ་ཤླཽ་ཀ་གཅིག དམར་པོ་སྐོར་གསུམ་ལ་བསྟོད་པ་ཤླཽ་ཀ་གཅིག
        མངའ་རིས་རྒྱལ་པོ་ལ་གནང་བའི་བསྟོད་པ། རྗེ་ཉིད་ཀྱི་བུ་སློབ་སོགས་དད་གསོའི་བསྐུལ་བའི་ངོར་མཛད་པ་ལ།
        བྱང་པ་བདག་ཆེན་ཀུན་དགའ་བཀྲ་ཤིས་པ་ལ་བསྟོད་པ། གུག་གེ་གཞི་སྡེ་པ་ནམ་མཁའ་བརྟན་པ་ལ་བསྟོད་པ།
        དཔལ་འཁོར་བདེ་ཆེན་གྱི་མཁན་པོ་དཀོན་མཆོག་ཚུལ་ཁྲིམས་ལ་བསྟོད་པ། ལོ་དགོན་པའི་སྤྱན་སྔ་ལ་བསྟོད་པ།
        བློ་གྲོས་རབ་གསལ་ལ་བསྟོད་པ་ཤླཽ་ཀ་གཅིག ཆོས་རྗེ་མགོན་པོ་དབང་ཕྱུག་ལ་བསྟོད་པ་ཤླཽ་ཀ་གཅིག
        ཐུབ་བསྟན་རྣམ་རྒྱལ་གྱི་གདན་ས་པ་བཀྲ་ཤིས་བརྟན་པ་ལ་བསྟོད་པ། ཆོས་རྗེ་དཔལ་ལྡན་རྒྱལ་མཚན་ལ་བསྟོད་པ།
        ཐུབ་བསྟན་ཡངས་པ་ཅན་གྱི་གདན་ས་པ་གྲགས་པ་མཚན་ལ་བསྟོད་པ། སྐྱེ་ཙ་མཁན་པོ་རྡོར་འཛིན་ལ་བསྟོད་པ།
        གཏིང་སྐྱེས་པ་ཆོས་རྗེ་ཀུན་དགའ་བཀྲ་ཤིས་ལ་བསྟོད་པ་ཤླཽ་ཀ་གཅིག ཆོས་རྗེ་རྡོ་རྗེ་སེང་གེ་ལ་བསྟོད་པ་ཤླཽ་ཀ་གཅིག
        ཉག་རོ་གསེར་མདོག་པའི་བླ་མ་ལ་བསྟོད་པ། ཇོ་ནང་མཁན་པོ་དཔལ་ལྡན་རིན་ཆེན་ལ་བསྟོད་པ།
        ཆོས་རྗེ་སངས་རྒྱས་རྒྱལ་མཚན་ལ་བསྟོད་པ་ཤླཽ་ཀ་གཅིག ཆོས་རྗེ་ཀུན་དགའ་རྒྱ་མཚོ་ལ་བསྟོད་པ་ཤླཽ་ཀ་གཅིག
        ཡང་ཇོ་ནང་མཁན་པོ་ལ་བསྟོད་པ་ཤླཽ་ཀ་གཅིག སྒྲུབ་པ་སངས་རྒྱས་དཔལ་ལ་བསྟོད་པ། སྒྲུབ་ཐབས་སྐོར་ལ་བླ་མ་རིན་ཆེན་འབྱུང་གི་སྒྲུབ་ཐབས།
        བིར་བསྲུང་ཐུན་མོང་མ་ཡིན་པའི་བསྒོམ་ཚུལ།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: 84cf.txt
      order: 14
    3a22:
      title: མྱུར་རྩིས་རྣམ་དག་སྐྱོན་མེད་ཉེར་མཁོ་ཀུན་གསལ།
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: 3a22.txt
      order: 15
    434e:
      title: བྱང་པ་བདག་ཆེན་ཀུན་དགའ་བཀྲ་ཤིས་པ་ཆེ་འདོན་མཛད་དུས་གནང་བའི་མོ་གཏམ་དགོས་པ་སྐབས་དོན།
        རྩེ་གདོང་པའི་དགེར་གྱི་གདུང་རབས། བསྔོ་བ་གཅིག
      author: ས་ལོ་ཆེན་པོ་འཇམ་དབྱངས་ཀུན་བསོད།
      base_file: 434e.txt
      order: 16
created_at: '2022-04-06T16:30:05.934807'
last_modified_at: '2022-04-06T16:30:05.934835'
